Remove the non-deterministic module export modification in native.ts
zeromq/zeromq.js pull request #391
Opened 2020-04-03 13:31 UTC by Eximius

In rare cases (notably jest), if it reloads the module cache for every test-suite, all test-suites that are run after the first one will have the `methods` dict have the values {send: undefined, received: undefined, ...}, because the ./native module itself is reloaded, however the node-gyp-build module is not (hence has the aforementioned dict keys of Socket.prototype deleted => undefined).

Instead of spelunking into figuring out how to make the previous very-non-standard semantics work, this seems like a simpler and more robust solution.

2020-06-08 15:42 UTC, lesmoutonssauvages commented
Thanks @Eximius , i wasn't crazy

2020-06-09 13:00 UTC, rolftimmermans commented
I'd be happy to merge this; but there seem to be some unrelated changes included. Could you update the PR so only the relevant code bits are modified?

2020-06-09 13:40 UTC, Eximius commented
I can remove the bumps, but the other changes would seemingly help in general?

2020-06-09 13:46 UTC, rolftimmermans commented
If there are any other issues you want to address feel free to open a separate pull request for them. Without any description it's not obvious why the other changes are needed.

2020-10-26 10:08 UTC, lesmoutonssauvages commented
Hi @rolftimmermans  and @Eximius, any new on this PR ? May i help to split commits?

2021-04-18 14:11 UTC, aminya requested changes

2021-04-18 14:11 UTC, aminya commented on package.json
> +  "version": "6.0.0-beta.11",
Please revert

2021-04-18 14:11 UTC, aminya commented on script/build.sh
> +#!/bin/bash
Isn't the script sh compliant?

2021-04-18 14:11 UTC, aminya commented on src/socket.cc
> +    //Warn(Env(), "Socket option will not take effect until next connect/bind.");
Why commenting this out?

2021-04-18 14:11 UTC, aminya commented on src/util.ts
> +    if (methods.indexOf(method) != -1) delete socketPrototype[method]
```suggestion
    if (methods.indexOf(method) !== -1) { 
      delete socketPrototype[method]
    }
```

2022-09-05 11:50 UTC, aminya commented on src/socket.cc
> +    // Warn(Env(), "Socket option will not take effect until next connect/bind.");
```suggestion
    Warn(Env(), "Socket option will not take effect until next connect/bind.");
```

2022-09-05 11:51 UTC, aminya approved these changes

2022-09-08 08:19 UTC, merged