Context aware
zeromq/zeromq.js pull request #482
Opened 2021-09-03 11:49 UTC by YZYLAB

Necessary for Electron 14.0

2021-09-29 17:03 UTC, aminya requested changes

2021-09-29 17:03 UTC, aminya commented on package.json
> +  "version": "5.2.9",
Could you revert this?

2021-09-30 09:49 UTC, YZYLAB commented on package.json
> +  "version": "5.2.9",
I think its fixed now

2022-04-01 14:01 UTC, nbabanov commented
@JustinTulloss @lgeiger

2022-04-10 23:03 UTC, captainsafia commented
Stepping into this with no context (pun intended).

> Necessary for Electron 14.0

Where is this documented?

Also, how do we validate this fix?

Not opposed to it on principle, but want to make sure I's are dotted and T's are crossed.

2022-04-11 07:43 UTC, YZYLAB commented
https://github.com/electron/electron/issues/18397 

Here they explained what they pushed in Electron 14.0

2022-08-25 10:12 UTC, nbabanov commented
@captainsafia Could you provide any info?

2022-08-25 10:25 UTC, aminya approved these changes

2022-08-25 10:25 UTC, merged