Fix: Remove libsodium dependency (for now).
zeromq/zeromq.js pull request #554
Opened 2023-01-05 16:21 UTC by Bartel-C8

Use TweetNacl, which doesn't need a (user having) libsodium installed.

As discussed here: https://github.com/zeromq/zeromq.js/issues/529#issuecomment-1370721089 , libzmq doesn't handle statically linking `libsodium`.

I think the best, and most versatile option (keeping in mind all build platforms: Unix, Alpine, macOS x64, macOS ARM, Windows x64, Windows ARM, ...), as a next step, to build libsodium ourselves in the build.ts, before `libzmq` itself. Preferably with `libsodium-cmake` (https://github.com/robinlinden/libsodium-cmake) .

2023-01-05 16:23 UTC, Bartel-C8 commented
@aminya : What do you think about it? The current released beta really has issues/problems with installing. So I would prefer having a new beta release with tweetnacl. So we can fix this decently but at ease...

2023-01-05 20:14 UTC, aminya requested changes
A better solution is to include the dylib/so files in the package. I don't think removing it is a good idea.

2023-01-05 20:32 UTC, Bartel-C8 commented
I do agree that it's not ideal to remove it. But how were the beta-6 and earlier shipped? Without libsodium I guess?

Also, dynamic linking in combination with .node files will be cumbersome for the many platforms I think: https://github.com/nodejs/node-gyp/issues/89 (I am an electron user, so I have a big focus on that)

So a static build of libsodium will be the most easy/stable/versatile I guess...

But this PR was to quickly address the failing install of the current released beta. And even the case I had on macOS, where the shipped .node in my electron build has a hard dependency on libsodium installed on the client. Without being bundled currently... 

So I had runtime crashes at clients, without noticing at first, as my own environment is the build environment l, which had libsodium installed...

2023-01-05 20:59 UTC, Bartel-C8 commented
Btw, currently, the windows build is built without libsodium, as it is not installed on the CI. So it's not uniform anyway now. That is why I thought this PR is a good first step.

I do completely agree, that for the official 6.0 release, this should be resolved. But like said, the current beta release is not really usable currently, both for macOS as for Linux...

2023-01-18 14:51 UTC, Bartel-C8 commented
@aminya : As the upstream issue in libzmq was not accepted (initially hopefully) this will take time. And so the latest published build is not usable for all OSses. So I am in favour of merging this PR for a temporary working solution at least...

2023-10-24 08:19 UTC, mitchobrian commented
Do we have a timescale for this?

2023-11-15 04:46 UTC, pshenmic commented
I'm having different issues on Node 20 with zeromq 6.0.0-beta.17 on the CI and in the Docker images:

```
 /opt/actions-runner/_work/_tool/node/20.9.0/arm64/bin/node: symbol lookup error: /opt/actions-runner/_work/platform/platform/.yarn/unplugged/zeromq-npm-6.0.0-beta.17-8f82236e6c/node_modules/zeromq/build/Release/zeromq.node: undefined symbol: sodium_init
```

```
Error: Error relocating /platform/.yarn/unplugged/zeromq-npm-6.0.0-beta.17-8f82236e6c/node_modules/zeromq/build/Release/zeromq.node: crypto_box_easy_afternm: symbol not found
```

We really need get this PR in

2023-11-15 07:54 UTC, aminya approved these changes

2023-11-15 07:54 UTC, merged

2023-11-15 08:06 UTC, Bartel-C8 commented
Thanks @aminya , in name of the zmq.js community ;-). 

Should we mention that CURVE is disabled then in the README? 
A new release would befit many then from now on! 🙏

2023-11-15 08:09 UTC, mitchobrian commented
Will it be 6.0.0-beta.18  ?